version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: yangchengjian/frigate:0.8.4-amd64
    devices:
      - /dev/bus/usb:/dev/bus/usb
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/yangchengjian/sft/frigate/config:/config
      - /Users/yangchengjian/sft/frigate/media:/media
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_VIEWER: "guest"
      FRIGATE_RTSP_PASSWORD: "yangjian0101"